version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          gh-actions:
              applies-to: version-updates
              update-types:
                  - 'minor'
                  - 'patch'
          gh-actions-security:
              applies-to: security-updates
              update-types:
                  - 'minor'
                  - 'patch'

    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          angular:
              applies-to: version-updates
              patterns:
                  - '@angular/*'
                  - '@angular-devkit/*'
                  - '@angular-eslint/*'
                  - 'angular-eslint'
              update-types:
                  - 'minor'
                  - 'patch'
          nx:
              applies-to: version-updates
              patterns:
                  - '@nx/*'
                  - '@nrwl/*'
                  - 'nx'
                  - 'nx-electron'
              update-types:
                  - 'minor'
                  - 'patch'
          npm:
              applies-to: version-updates
              exclude-patterns:
                  - '@angular/*'
                  - '@angular-devkit/*'
                  - '@angular-eslint/*'
                  - 'angular-eslint'
                  - '@nx/*'
                  - '@nrwl/*'
                  - 'nx'
              update-types:
                  - 'minor'
                  - 'patch'
          npm-security:
              applies-to: security-updates
              update-types:
                  - 'minor'
                  - 'patch'

    - package-ecosystem: 'cargo'
      directory: '/apps/metadata-engine'
      schedule:
          interval: 'weekly'
      groups:
          cargo:
              applies-to: version-updates
              update-types:
                  - 'minor'
                  - 'patch'
          cargo-security:
              applies-to: security-updates
              update-types:
                  - 'minor'
                  - 'patch'
