version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          gh-actions:
              applies-to: version-updates
              update-types:
                  - 'minor'
                  - 'patch'
          gh-actions-security:
              applies-to: security-updates
              update-types:
                  - 'minor'
                  - 'patch'

    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          npm:
              applies-to: version-updates
              update-types:
                  - 'minor'
                  - 'patch'
          npm-security:
              applies-to: security-updates
              update-types:
                  - 'minor'
                  - 'patch'

    - package-ecosystem: 'cargo'
      directory: '/apps/metadata-engine'
      schedule:
          interval: 'weekly'
      groups:
          cargo:
              applies-to: version-updates
              update-types:
                  - 'minor'
                  - 'patch'
          cargo-security:
              applies-to: security-updates
              update-types:
                  - 'minor'
                  - 'patch'
