// Generated by tools/design-tokens.cjs. Do not edit.
export const semanticColorIdentifiers = [
    "background.canvas",
    "background.surface",
    "background.elevated",
    "background.overlay",
    "content.primary",
    "content.secondary",
    "content.muted",
    "content.inverse",
    "content.action",
    "content.success",
    "content.warning",
    "content.danger",
    "content.info",
    "border.subtle",
    "border.default",
    "border.strong",
    "border.focus",
    "action.primary",
    "action.primary-hover",
    "action.primary-pressed",
    "action.primary-disabled",
    "action.primary-content",
    "action.secondary",
    "action.secondary-hover",
    "action.secondary-pressed",
    "action.secondary-content",
    "action.quiet-hover",
    "action.quiet-pressed",
    "status.success-background",
    "status.success-hover",
    "status.success-content",
    "status.success-border",
    "status.warning-background",
    "status.warning-hover",
    "status.warning-content",
    "status.warning-border",
    "status.danger-background",
    "status.danger-hover",
    "status.danger-content",
    "status.danger-border",
    "status.info-background",
    "status.info-hover",
    "status.info-content",
    "status.info-border"
] as const

export type SemanticColorIdentifier = (typeof semanticColorIdentifiers)[number]

export const semanticColor = (identifier: SemanticColorIdentifier): string =>
    `var(--color-${identifier.replace(/\./g, '-')})`

export const contrastPairs = [
    [
        "content.primary",
        "background.canvas"
    ],
    [
        "content.primary",
        "background.surface"
    ],
    [
        "content.secondary",
        "background.canvas"
    ],
    [
        "content.secondary",
        "background.surface"
    ],
    [
        "content.muted",
        "background.canvas"
    ],
    [
        "content.action",
        "background.canvas"
    ],
    [
        "action.primary-content",
        "action.primary"
    ],
    [
        "status.success-content",
        "status.success-background"
    ],
    [
        "status.warning-content",
        "status.warning-background"
    ],
    [
        "status.danger-content",
        "status.danger-background"
    ],
    [
        "status.info-content",
        "status.info-background"
    ]
] as const

export const foundationColorIdentifiers = [
    "color.purple.100",
    "color.purple.200",
    "color.purple.300",
    "color.purple.400",
    "color.purple.500",
    "color.purple.600",
    "color.purple.700",
    "color.purple.800",
    "color.purple.900",
    "color.green.100",
    "color.green.200",
    "color.green.300",
    "color.green.400",
    "color.green.500",
    "color.green.600",
    "color.green.700",
    "color.green.800",
    "color.green.900",
    "color.neutral.100",
    "color.neutral.200",
    "color.neutral.300",
    "color.neutral.400",
    "color.neutral.500",
    "color.neutral.600",
    "color.neutral.700",
    "color.neutral.800",
    "color.neutral.900",
    "color.danger.100",
    "color.danger.200",
    "color.danger.300",
    "color.danger.400",
    "color.danger.500",
    "color.danger.600",
    "color.danger.700",
    "color.danger.800",
    "color.danger.900",
    "color.warning.100",
    "color.warning.200",
    "color.warning.300",
    "color.warning.400",
    "color.warning.500",
    "color.warning.600",
    "color.warning.700",
    "color.warning.800",
    "color.warning.900"
] as const
export const spacingTokenIdentifiers = [
    "spacing.0",
    "spacing.1",
    "spacing.2",
    "spacing.3",
    "spacing.4",
    "spacing.5",
    "spacing.6",
    "spacing.8",
    "spacing.10",
    "spacing.12",
    "spacing.16",
    "spacing.22",
    "spacing.24",
    "spacing.32",
    "spacing.52",
    "spacing.64",
    "spacing.px",
    "spacing.0.5",
    "spacing.1.5",
    "spacing.2.5"
] as const
export const radiusTokenIdentifiers = [
    "radius.none",
    "radius.sm",
    "radius.md",
    "radius.lg",
    "radius.xl",
    "radius.full"
] as const
export const sizeTokenIdentifiers = [
    "size.control-sm",
    "size.control-md",
    "size.control-lg",
    "size.icon-sm",
    "size.icon-md",
    "size.icon-lg",
    "size.icon-xl"
] as const
export const opacityTokenIdentifiers = [
    "opacity.0",
    "opacity.30",
    "opacity.50",
    "opacity.70",
    "opacity.100"
] as const
export const shadowTokenIdentifiers = [
    "shadow.sm",
    "shadow.md",
    "shadow.lg",
    "shadow.focus",
    "shadow.success-glow",
    "shadow.danger-glow"
] as const
export const typographyVariantIdentifiers = [
    "hero-title",
    "section-title",
    "body-md",
    "body-sm",
    "label-md",
    "label-sm",
    "code-sm"
] as const

export const foundationToken = (identifier: string): string =>
    `var(--foundation-${identifier.replace(/\./g, '-').replace(/lineHeight/g, 'line-height')})`
