name: 'Build'

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

    workflow_dispatch:

permissions:
    contents: read

jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/setup-node
            - name: Install linux dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

            - name: Build the app
              run: make package

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  name: linux-build
                  path: dist/executables/

    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/setup-node
              with:
                  install-command: npm i && npm i -D cli-truncate iconv-corefoundation

            - name: Build the app
              run: make package

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  name: macos-build
                  path: dist/executables/*.dmg

    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/setup-node

            - name: Build the app
              run: make package

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  name: windows-build
                  path: dist/executables/
